### ISSUE TITLE
Can't generate the report

### ISSUE THREAD

**Issue by ArthurAlvarez** [nakiostudio/xcov#91] opened 2017-04-20 13:19 UTC
Hello, I am currently trying to use xcov as a post execution script on a Xcode bot for CI.

The xcov script works well on my local machine, but when Xcode runs it on the server I get the following result:

[10:10:18]: [4m[36m$ xcodebuild -list -workspace Next\ App.xcworkspace[0m[0m

+-----------------------------+------------------------------------------------------------------------------------------+
|                                                 [32mSummary for xcov 1.2.0[0m                                                 |
+-----------------------------+------------------------------------------------------------------------------------------+
| workspace                   | Next App.xcworkspace                                                                     |
| scheme                      | Next App                                                                                 |
| output_directory            | /Users/ifood/Public/Drop Box                                                             |
| derived_data_path           | /Users/ifood/Library/Caches/XCSBuilder/Bots/316d4af48eb74f57c380c88679ad949a/DerivedData |
| html_report                 | true                                                                                     |
| markdown_report             | false                                                                                    |
| json_report                 | false                                                                                    |
| minimum_coverage_percentage | 0                                                                                        |
| skip_slack                  | false                                                                                    |
| slack_username              | xcov                                                                                     |
| slack_message               | Your *xcov* coverage report                                                              |
| ignore_file_path            | ./.xcovignore                                                                            |
| include_test_targets        | false                                                                                    |
| only_project_targets        | false                                                                                    |
+-----------------------------+------------------------------------------------------------------------------------------+

[10:10:20]: [4m[36m$ /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov-core/bin/xcov-core -s /Users/ifood/Library/Caches/XCSBuilder/Bots/316d4af48eb74f57c380c88679ad949a/DerivedData/Logs/Test/256EEBA4-D03A-4B13-8504-C41443936587.xccoverage -o /var/folders/v4/qz1fqlhd6kzd6v5d5wcskv0w0000gn/T/report.json20170420-56524-1wex3x9 --include-lines-info[0m[0m
[10:10:20]: ▸ [35mLoading...[0m
[10:10:20]: ▸ [35m------ xcov-core ------[0m
[10:10:20]: ▸ [35mOpening .xccoverage file at path: /Users/ifood/Library/Caches/XCSBuilder/Bots/316d4af48eb74f57c380c88679ad949a/DerivedData/Logs/Test/256EEBA4-D03A-4B13-8504-C41443936587.xccoverage[0m
[10:10:20]: ▸ [35mParsing .xccoverage file...[0m
[10:10:20]: ▸ [35mFile successfully parsed[0m
[10:10:20]: ▸ [35mSerializing coverage report...[0m
[10:10:20]: ▸ [35mReport successfully serialized[0m
[10:10:20]: ▸ [35mWriting report on disk...[0m
[10:10:20]: ▸ [35mCoverage report successfully created at path: /var/folders/v4/qz1fqlhd6kzd6v5d5wcskv0w0000gn/T/report.json20170420-56524-1wex3x9[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `encode': [31m[!] "\xC2" on US-ASCII[0m (Encoding::InvalidByteSequenceError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov-core.rb:20:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov/manager.rb:46:in `parse_xccoverage'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov/manager.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.27.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov/commands_generator.rb:46:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/lib/xcov/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/xcov-1.2.0/bin/xcov:6:in `<top (required)>'
	from /usr/local/bin/xcov:23:in `load'
	from /usr/local/bin/xcov:23:in `<main>'

--------------
How can I resolve this issue?

Thank you

**Comment by michaelharro** [comment] 2017-05-24 22:22
I am also experiencing the same problem.

It is caused by the use of the tempfile gem here https://github.com/nakiostudio/xcov/blob/b4d00172e7277adae5f28f8fe36c19af33600499/lib/xcov/coveralls_handler.rb#L54 and here https://github.com/nakiostudio/xcov/blob/b4d00172e7277adae5f28f8fe36c19af33600499/lib/xcov-core.rb#L15

The tempfile gem requires you to have read and write access to subdirectories of `/var` which you don't on a lot of CI services. I personally am using travis for one of my projects and travis does not give you access to the directory tempfile uses.

The simplist solution would be to have these temporary files locate themselves in a subdirectory of the xcov output directory. e.g. `/path/to/xcov_report/tmp` which would then get removed at the end of xcov's execution.

@nakiostudio I am not sure if there are any unintended effects to this solution. If you are happy with my suggested solution I would be happy to submit a PR to fix this.

**Comment by nakiostudio** [comment] 2017-07-15 08:52
Closing as @michaelharro has fixed the issue. Will be shipped in the next version 👍

**Closed by nakiostudio** 2017-07-15 08:52 UTC
