### ISSUE TITLE
Bitrise: Could not find option for key :workspace. Available keys:

### ISSUE THREAD

**Issue by Zaccc123** [nakiostudio/xcov#73] opened 2017-01-25 03:23 UTC
Somehow, Using `fastlane` on `Bitrise` cause `xcov` to fail without the option key `:workspace`. It work locally on my machine. Anyone have any possible leads why this would happen?

<img width="875" alt="screen shot 2017-01-25 at 11 19 12 am" src="https://cloud.githubusercontent.com/assets/11663635/22276728/a1e658e0-e2f0-11e6-98d2-01a9b0fd77a5.png">

**Comment by nakiostudio** [comment] 2017-01-25 08:41
Hey @Zaccc123 👋 

Thanks for reporting, this one is a weird one. Can I take a look at how are you setting xcov up on your Fastfile?

**Comment by Zaccc123** [comment] 2017-01-25 09:21
xcov(
      workspace: "wit-reader.xcworkspace",
      scheme: "wit-reader-dev",
      output_directory: "xcov_output",
      include_targets: "wit-reader.app",
      slack_channel: "#wit-integration",
      slack_url: SLACK_WEBHOOK_URL
    )

Hey @nakiostudio the above is my setup. By the way, great work on the this, let me know if you need more information. Cheers =)

**Comment by nakiostudio** [comment] 2017-01-25 09:48
Thank you @Zaccc123 !

Your setup looks good to me, does this only happen on Bitrise and not in your local machine? which `xcov` and `fastlane` versions are you using?

**Comment by Zaccc123** [comment] 2017-01-26 06:59
Yes, it happen only on `Bitrise` and not my local machine. Both are using the same version, thats why I find it weird that it fail on `Bitrise`.

`fastlane 2.11.0`, `xcov 1.0.0`

**Comment by thelvis4** [comment] 2017-01-26 08:55
@Zaccc123 Do you know by any chance what version of Rubygems (`gem --version`) is used on Bitrise?

@nakiostudio I think xcov action reaches [this line](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/xcov.rb#L38) and that's why we don't get back the available actions.
We had this kind of issues with Rubygems 2.6.2 which was fixed with this [monkey_patch](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/core_ext/bundler_monkey_patch.rb#L3).
I think it would be helpful to have a log like 
`UI.important "Couldn't find 'xcov' gem specification.`
in `xcov` action inside of the `rescue` block.

**Comment by Zaccc123** [comment] 2017-01-26 10:30
I believe it is `2.3.0`. I did manage to temporary solve it by installing `xcov` first by using the Ruby Script plugin to run `gem 'xcov'`. 

The difference is that this install `xcov` first rather than installing it while `fastlane` running. Not sure if that would be the causes.

**Comment by nakiostudio** [comment] 2017-01-27 09:44
As @thelvis4 pointed out this should affect version `2.6.2` of ruby gems only. I will run some tests over the weekend 👍

**Comment by nakiostudio** [comment] 2017-01-29 10:50
I am not able to reproduce this scenario with Rubygems 2.3.0. I will close the ticket as you found a workaround for the problem.

**Closed by nakiostudio** 2017-01-29 10:50 UTC

**Comment by Zaccc123** [comment] 2017-01-31 02:20
Okay.. I will update here if I manage to find more information about it. Thanks for your time =)
